"""Sentry: the audit's scope, the controls, and the seed.

The subject is a fictional company, Mekar Holdings Berhad, with four systems that
hold user access: the ERP (finance, procurement, payments), the HR system, the
payroll system and the Windows domain (AD). The data is synthetic — generated by
`sentry/generate.py` from SEED with known control failures injected and recorded —
because no real identity-and-access extract is public. The tests are real: they are
the tests an IT auditor runs on a real extract, and the ground truth lets the audit
say how many of the injected failures each test caught.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
RESULTS = ROOT / "results"
MARTS = ROOT / "frontend" / "data"

SEED = 20260921
COMPANY = "Mekar Holdings Berhad"
PERIOD_START = date(2025, 7, 1)
PERIOD_END = date(2026, 6, 30)
AS_OF = date(2026, 6, 30)          # the date of the access extract
FIELDWORK = date(2026, 9, 21)

SYSTEMS = {
    "ERP": "Finance, procurement and payments (SAP-like)",
    "HRIS": "HR records, positions, leave",
    "PAYROLL": "Payroll run and bank file",
    "AD": "Windows domain: network logon, email, file shares",
}

DEPARTMENTS = ["Finance", "Procurement", "Human Resources", "IT", "Operations", "Sales", "Legal", "Facilities"]

# Role-based access: each job role maps to the entitlements it should have.
# An entitlement is SYSTEM:role. Anything outside the list for a role is an
# "excess" entitlement unless an approved exception exists.
ROLE_ENTITLEMENTS: dict[str, list[str]] = {
    "AP Clerk": ["AD:user", "ERP:ap_invoice_entry", "ERP:vendor_view"],
    "AP Supervisor": ["AD:user", "ERP:ap_invoice_entry", "ERP:ap_invoice_approve", "ERP:vendor_view"],
    "AR Clerk": ["AD:user", "ERP:ar_receipts", "ERP:customer_view"],
    "Treasury Officer": ["AD:user", "ERP:payment_run", "ERP:bank_recon", "ERP:vendor_view"],
    "Financial Accountant": ["AD:user", "ERP:gl_journal_post", "ERP:gl_reporting"],
    "Finance Manager": ["AD:user", "ERP:gl_journal_approve", "ERP:gl_reporting", "ERP:payment_approve", "ERP:ap_invoice_approve"],
    "Procurement Officer": ["AD:user", "ERP:po_create", "ERP:vendor_view"],
    "Procurement Manager": ["AD:user", "ERP:po_approve", "ERP:vendor_create", "ERP:vendor_view"],
    "Vendor Master Admin": ["AD:user", "ERP:vendor_create", "ERP:vendor_view"],
    "HR Officer": ["AD:user", "HRIS:employee_edit", "HRIS:employee_view"],
    "HR Manager": ["AD:user", "HRIS:employee_edit", "HRIS:employee_view", "HRIS:position_approve", "PAYROLL:payroll_view"],
    "Payroll Officer": ["AD:user", "PAYROLL:payroll_run", "PAYROLL:payroll_view", "HRIS:employee_view"],
    "Payroll Manager": ["AD:user", "PAYROLL:payroll_approve", "PAYROLL:bank_file_release", "PAYROLL:payroll_view", "HRIS:employee_view"],
    "IT Support": ["AD:user", "AD:helpdesk"],
    "IT Administrator": ["AD:user", "AD:domain_admin"],
    "ERP Basis Administrator": ["AD:user", "ERP:sap_all"],
    "Operations Staff": ["AD:user"],
    "Operations Manager": ["AD:user", "ERP:po_create", "ERP:gl_reporting"],
    "Sales Executive": ["AD:user", "ERP:customer_view", "ERP:ar_receipts"],
    "Sales Manager": ["AD:user", "ERP:customer_view", "ERP:gl_reporting"],
    "Legal Counsel": ["AD:user"],
    "Facilities Staff": ["AD:user"],
    "Executive": ["AD:user", "ERP:gl_reporting", "PAYROLL:payroll_view"],
}

# Which roles belong to which department, with a rough headcount weight.
DEPARTMENT_ROLES: dict[str, list[tuple[str, int]]] = {
    "Finance": [("AP Clerk", 10), ("AP Supervisor", 2), ("AR Clerk", 6), ("Treasury Officer", 3), ("Financial Accountant", 6), ("Finance Manager", 2), ("Executive", 1)],
    "Procurement": [("Procurement Officer", 8), ("Procurement Manager", 2), ("Vendor Master Admin", 2)],
    "Human Resources": [("HR Officer", 6), ("HR Manager", 2), ("Payroll Officer", 3), ("Payroll Manager", 1)],
    "IT": [("IT Support", 8), ("IT Administrator", 4), ("ERP Basis Administrator", 2)],
    "Operations": [("Operations Staff", 60), ("Operations Manager", 6)],
    "Sales": [("Sales Executive", 20), ("Sales Manager", 3), ("Executive", 1)],
    "Legal": [("Legal Counsel", 2)],
    "Facilities": [("Facilities Staff", 12)],
}

PRIVILEGED = {"AD:domain_admin", "ERP:sap_all", "PAYROLL:bank_file_release"}

# Segregation of duties: pairs of entitlements one person must not hold together,
# with the fraud each combination enables.
SOD_RULES: list[tuple[str, str, str]] = [
    ("ERP:vendor_create", "ERP:payment_run", "Create a vendor and pay it"),
    ("ERP:vendor_create", "ERP:ap_invoice_entry", "Create a vendor and enter its invoices"),
    ("ERP:ap_invoice_entry", "ERP:ap_invoice_approve", "Enter and approve the same invoice"),
    ("ERP:po_create", "ERP:po_approve", "Raise and approve the same purchase order"),
    ("ERP:payment_run", "ERP:payment_approve", "Prepare and approve the same payment run"),
    ("ERP:gl_journal_post", "ERP:gl_journal_approve", "Post and approve the same journal"),
    ("ERP:payment_run", "ERP:bank_recon", "Pay and reconcile the bank"),
    ("HRIS:employee_edit", "PAYROLL:payroll_run", "Create an employee and pay them"),
    ("PAYROLL:payroll_run", "PAYROLL:payroll_approve", "Run and approve the same payroll"),
    ("PAYROLL:payroll_approve", "PAYROLL:bank_file_release", "Approve payroll and release the bank file"),
    ("AD:domain_admin", "ERP:payment_run", "Administer the domain and run payments"),
    ("ERP:sap_all", "ERP:payment_approve", "Full ERP authority and payment approval"),
]

LEAVER_DEADLINE_DAYS = 1       # accounts disabled by the next business day
DORMANT_DAYS = 90              # no logon in 90 days
TOLERABLE_RATE = 0.05          # the exception rate above which a control is not relied upon
EXPENSE_APPROVAL_LIMIT = 1000  # RM; claims above need a second approver

CONTROLS = [
    {
        "id": "A1", "name": "Joiners: every account belongs to a current employee",
        "objective": "No account exists without a person in HR to own it, and none was created before that person joined.",
        "test": "Join every account on the four systems to the HR master by employee ID; flag accounts with no HR record, or created before the hire date.",
        "population": "Accounts on the extract as at 30 June 2026",
        "frameworks": {"COBIT 2019": "DSS05.04 Manage user identity and logical access", "ISO/IEC 27001:2022": "A.5.16 Identity management", "SOX ITGC": "Logical access — access is provisioned to authorised users"},
    },
    {
        "id": "A2", "name": "Leavers: access is removed when employment ends",
        "objective": "A terminated employee's accounts are disabled by the next business day.",
        "test": "For every employee terminated in the period, every account they held: disabled on or before termination + 1 business day; still enabled at the extract date is a failure, disabled late is a failure.",
        "population": "Accounts of employees terminated 1 July 2025 – 30 June 2026",
        "frameworks": {"COBIT 2019": "DSS05.04", "ISO/IEC 27001:2022": "A.5.18 Access rights; A.6.5 Responsibilities after termination", "SOX ITGC": "Logical access — access is removed timely on termination"},
    },
    {
        "id": "A3", "name": "Movers: access matches the current role",
        "objective": "An employee holds only the entitlements the role-based access model assigns to their current role, or an approved exception.",
        "test": "Compare each active employee's entitlements to ROLE_ENTITLEMENTS for their current role; excess entitlements without an approved exception ticket are failures. Employees who changed role in the period are reported separately: their excess is what the move left behind.",
        "population": "Active employees at the extract date",
        "frameworks": {"COBIT 2019": "DSS05.04; DSS06.03 Manage roles, responsibilities, access privileges", "ISO/IEC 27001:2022": "A.5.15 Access control; A.5.18", "SOX ITGC": "Logical access — access is appropriate to job responsibilities"},
    },
    {
        "id": "A4", "name": "Privileged access is restricted and named",
        "objective": "Domain admin, ERP SAP_ALL and payroll bank-file release are held only by roles entitled to them, on named accounts.",
        "test": "Every privileged entitlement: the holder's role includes it, the account is a named personal account (not generic or shared), and the holder is an active employee.",
        "population": "Privileged entitlements on the extract",
        "frameworks": {"COBIT 2019": "DSS05.04 (privileged access)", "ISO/IEC 27001:2022": "A.8.2 Privileged access rights", "SOX ITGC": "Logical access — privileged access is restricted"},
    },
    {
        "id": "A5", "name": "Dormant accounts are disabled",
        "objective": "An enabled account that has not been used in 90 days is disabled.",
        "test": "Enabled accounts with last logon more than 90 days before the extract date, or never used and created more than 90 days before it.",
        "population": "Enabled accounts on the extract",
        "frameworks": {"COBIT 2019": "DSS05.04", "ISO/IEC 27001:2022": "A.5.18 Access rights (review and removal)", "SOX ITGC": "Logical access — periodic review"},
    },
    {
        "id": "A6", "name": "Access changes are authorised",
        "objective": "Every grant of an entitlement in the period was requested in a ticket and approved by someone other than the requester or the beneficiary.",
        "test": "Every grant event in the period: a ticket exists, its status is approved, the approver is not the beneficiary and not the requester, and the approver is a manager or the system owner.",
        "population": "Grant events 1 July 2025 – 30 June 2026",
        "frameworks": {"COBIT 2019": "DSS05.04; BAI06 (for access as a change)", "ISO/IEC 27001:2022": "A.5.18 Access rights (provisioning)", "SOX ITGC": "Logical access — access requests are approved"},
    },
    {
        "id": "S1", "name": "Segregation of duties",
        "objective": "No one holds a combination of entitlements that lets them complete a fraud alone.",
        "test": "For every active employee, every SOD_RULES pair held together, across systems; a conflict without a documented mitigating control is a failure.",
        "population": "Active employees at the extract date",
        "frameworks": {"COBIT 2019": "DSS06.03 Segregation of duties", "ISO/IEC 27001:2022": "A.5.3 Segregation of duties", "SOX ITGC": "Segregation of duties within key financial processes"},
    },
    {
        "id": "F1", "name": "Expense claims: fraud analytics",
        "objective": "Not a control test — a set of analytics on the year's expense claims that an auditor runs to direct substantive work.",
        "test": "Benford's law on first digits, by department; claims just under the approval limit; duplicate claims (same claimant, amount and date); claims approved by the claimant; round-amount frequency.",
        "population": "Expense claims 1 July 2025 – 30 June 2026",
        "frameworks": {"COBIT 2019": "DSS06.04 Manage errors and exceptions", "ISO/IEC 27001:2022": "—", "SOX ITGC": "— (substantive analytics)"},
    },
]
